### ISSUE TITLE
Testsuite failing starting with 7.0.0rc1

### ISSUE THREAD

**Issue by glaubitz** [microsoft/knack#188] opened 2020-04-02 15:32 UTC
Starting with version ```7.0.0rc1```, the testsuite is failing for me on openSUSE Tumbleweed:

```
[   35s] =================================== FAILURES ===================================
[   35s] ________________________ TestOutput.test_out_yaml_byte _________________________
[   35s] 
[   35s] self = <tests.test_output.TestOutput testMethod=test_out_yaml_byte>
[   35s] 
[   35s]         def test_out_yaml_byte(self):
[   35s]             output_producer = OutputProducer(cli_ctx=self.mock_ctx)
[   35s]             output_producer.out(CommandResultItem({'active': True, 'contents': b'0b1f6472'}),
[   35s]                                 formatter=format_yaml, out_file=self.io)
[   35s]             self.assertEqual(normalize_newlines(self.io.getvalue()), normalize_newlines(
[   35s]                 """active: true
[   35s]     contents: !!binary |
[   35s]       MGIxZjY0NzI=
[   35s] >   """))
[   35s] E   AssertionError: 'active: true\ncontents: 0b1f6472\n' != 'active: true\ncontents: !!binary |\n  MGIxZjY0NzI=\n'
[   35s] 
[   35s] tests/test_output.py:132: AssertionError
[   35s] _____________________ TestOutput.test_out_yaml_byte_empty ______________________
[   35s] 
[   35s] self = <tests.test_output.TestOutput testMethod=test_out_yaml_byte_empty>
[   35s] 
[   35s]         def test_out_yaml_byte_empty(self):
[   35s]             output_producer = OutputProducer(cli_ctx=self.mock_ctx)
[   35s]             output_producer.out(CommandResultItem({'active': True, 'contents': b''}),
[   35s]                                 formatter=format_yaml, out_file=self.io)
[   35s]             self.assertEqual(normalize_newlines(self.io.getvalue()), normalize_newlines(
[   35s]                 """active: true
[   35s]     contents: !!binary ""
[   35s] >   """))
[   35s] E   AssertionError: "active: true\ncontents: ''\n" != 'active: true\ncontents: !!binary ""\n'
[   35s] 
[   35s] tests/test_output.py:141: AssertionError
[   35s] =============== 2 failed, 190 passed, 40 skipped in 1.54 seconds ===============
```

This is rather unfortunate as version ```7.0.0rc1``` is a dependency of the latest version of ```azure-cli``` ```2.3.1```.

CC @jiasli

**Comment by yonzhan** [comment] 2020-04-03 01:58
add to S168

**Comment by jiasli** [comment] 2020-04-03 02:08
May I know the Python version you are using? Is it Python 2? We have officially dropped Python 2 and 3.5 support (https://github.com/microsoft/knack/pull/174). 

According to https://pyyaml.org/wiki/PyYAMLDocumentation#cb7:

> `bytes` objects are converted to `!!binary` nodes.

That's why the result from the test is `'active: true\ncontents: 0b1f6472\n'`, but Knack is expecting `'active: true\ncontents: !!binary |\n  MGIxZjY0NzI=\n'`.

[Our CI also passed](https://travis-ci.org/github/microsoft/knack/builds/665779037?utm_source=github_status&utm_medium=notification) indicating the test suite is correct.

**Comment by yonzhan** [comment] 2020-04-18 08:42
@glaubitz was your issue resolved by above?

**Comment by glaubitz** [comment] 2020-04-21 06:22
Yes, the test fails on Python 2.7. We have switched the package to Python3-only.

FWIW, we are still supporting Python 2.7 in SLE-12 and Microsoft asks us to keep the Azure SDK plus Azure CLI up-to-date in SLE-12 as well for the SLE-12 Azure cloud images.

So Azure SDK and CLI being bleeding edge on their dependencies actually makes it harder to keep maintaining the Azure SDK and CLI for SLE-12. As it's an enterprise distribution, we cannot easily update packages to their latest versions - it's a complicated and long process.

**Comment by jiasli** [comment] 2020-04-21 06:57
I am glad the issue is solved. However, as Python 2 has been [deprecate](https://www.python.org/doc/sunset-python-2/) and no further security update is provided, we decided to remove Python 2 as a dependency. This is really something out of our control. Thanks for understanding.

**Closed by jiasli** 2020-04-21 06:57 UTC
